# Generated by Django 2.1 on 2018-09-03 16:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Panel',
            fields=[
                ('ID', models.CharField(max_length=24, primary_key=True, serialize=False, verbose_name='ID')),
                ('PanelName', models.CharField(max_length=32, verbose_name='Panel名称')),
                ('PanelVersion', models.CharField(max_length=32, verbose_name='版本号')),
                ('ExtField', models.TextField(blank=True, verbose_name='额外字段')),
                ('PanelNote', models.CharField(max_length=32, verbose_name='备注')),
            ],
            options={
                'verbose_name': '试剂盒',
                'verbose_name_plural': '试剂盒',
                'db_table': 'panel',
            },
        ),
        migrations.CreateModel(
            name='Sample',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SampleID', models.CharField(max_length=32, verbose_name='样本编号')),
                ('Name', models.CharField(max_length=32, verbose_name='姓名')),
                ('Gender', models.CharField(choices=[('男', '男'), ('女', '女')], max_length=1, verbose_name='性别')),
                ('ExtField', models.TextField(blank=True, verbose_name='额外字段')),
                ('Panel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sample.Panel')),
            ],
            options={
                'verbose_name': '样本',
                'verbose_name_plural': '样本',
                'db_table': 'sample',
            },
        ),
    ]
